apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
spec:
  nodeSelector: 
    internet: "true"
  volumes: 
  - name: mongodb-data
    nfs: 
      server: 9.110.74.145
      path: /var/k8nfs
  containers:
  - image: mongo
    name: mongodb
    volumeMounts: 
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP